# .github/workflows/preview.yml
# This is a basic workflow takes care of building and deploying
# catalog when creating merge request

name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

# do not allow running multiple of pipelines for this PR in parallel
concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      pull-requests: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Get commit message from PR head branch
        id: get_pr_commit_message
        run: |
          PR_COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          PR_REPO_OWNER=${{ github.event.pull_request.head.repo.owner.login }}
          PR_REPO_NAME=${{ github.event.pull_request.head.repo.name }}
          # Fetch the commit message from the PR's head branch
          COMMIT_MESSAGE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${PR_REPO_OWNER}/${PR_REPO_NAME}/commits/${PR_COMMIT_SHA}" \
            | jq -r .commit.message)
          # Setting skip flag.
           if [[ "$COMMIT_MESSAGE" == *"create session using empty commit"* ]]; then
            echo "should_skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_skip=false" >> "$GITHUB_OUTPUT"
          fi
      - name: changed-files
        id: changed-files
        uses: tj-actions/changed-files@v45
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: python .github/update_catalog_last_changes_pr.py
      - if: steps.get_pr_commit_message.outputs.should_skip != 'true'
        name: Build catalog
        env:
          SH_INSTANCE_ID: ${{ secrets.SH_INSTANCE_ID }}
          SH_CLIENT_ID: ${{ secrets.SH_CLIENT_ID }}
          SH_CLIENT_SECRET: ${{ secrets.SH_CLIENT_SECRET }}
        run: |
          docker pull ghcr.io/eodash/eodash_catalog:latest
          docker run -v "$PWD:/workspace" -w "/workspace" ghcr.io/eodash/eodash_catalog:latest eodash_catalog
      - if: steps.get_pr_commit_message.outputs.should_skip != 'true'
        name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build
